In [1]:
import tensorflow as tf
import numpy as np

In [3]:
from tensorflow.keras.utils import to_categorical

In [7]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test)= mnist.load_data()

In [8]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [9]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
x_train[5].dtype

dtype('uint8')

In [20]:
x_test[100]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 127,
        221,  52,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  64, 229,
        219, 104,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  13, 235, 140,
          4,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 118, 227,  25,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 236, 133,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  13, 243,  93,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  85, 243,  21,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 189, 236,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   1, 208, 169,   0,   0,
          0,   0,   0,   0,  64, 151, 151, 135,  74,   1,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  26, 254,  89,   0,   0,
          0,   0,   6, 142, 254, 224, 211, 181, 241,  70,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  26, 254,  68,   0,   0,
          0,   2, 161, 254, 104,   7,   0,   0,  80, 223,  15,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  57, 254,  15,   0,   0,
          0, 150, 231,  68,   1,   0,   0,   0,   9, 231,  26,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  79, 254,  15,   0,   0,
         24, 228,  66,   0,   0,   0,   0,   0,   0, 196,  87,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  73, 254,  43,   0,   0,
        116, 251,   7,   0,   0,   0,   0,   0,   0, 196, 100,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  13, 230, 147,   0,   0,
         60, 255,  70,   0,   0,   0,   0,   0,   4, 209,  84,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 203, 232,   4,   0,
         42, 253,  74,   0,   0,   0,   0,   0, 114, 233,  17,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  87, 252, 147,   0,
          0, 154, 229, 132, 123, 123,  63,  93, 248,  65,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 169, 249, 137,
         23,   8,  80, 100, 101, 107, 145, 192,  51,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   5, 139, 251,
        224, 144, 115, 115, 195, 254, 187,  48,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  55,
        141, 203, 244, 180, 129,  67,   2,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   

In [21]:
y_train[5]

2

In [23]:
y_test[100]

6

In [33]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])